name: xfactor_intelligent
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.9+39
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # core
  collection: ^1.17.0
  intl: ^0.18.1
  equatable: ^2.0.5

  # state management
  get: ^4.6.6
  #
  # load env
  flutter_dotenv: ^5.0.2

  # code generator
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # network
  dio: ^5.0.1
  graphql_flutter: ^5.1.2
  gql_dio_link: ^1.0.1+1
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8

  # preferences
  get_storage: ^2.1.1
  flutter_secure_storage: ^8.0.0

  # logging
  logger: ^1.2.2

  # device information
  device_info_plus: ^9.0.2
  android_id: ^0.3.3
  flutter_udid: ^2.0.1

  # file management
  path_provider: ^2.0.13

  # intent launcher
  url_launcher: ^6.1.10

  # Check connection
  connectivity_plus: ^5.0.2

  # firebase
  firebase_core: ^2.25.2
  firebase_messaging: ^14.7.13

  ## ==== UI ==== ##
  # UI
  flutter_screenutil: ^5.7.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.2
  pin_code_fields: ^8.0.1
  modal_bottom_sheet: ^3.0.0

  # Get image from camera or gallery
  image_picker: ^1.0.7
  file_picker: ^6.2.0

  # upload image
  minio_new: ^1.0.2

  # App version
  package_info_plus: ^8.0.1

  agora_uikit:
    path: ./dependencies/agora_uikit-1.3.7
  easy_count_timer: ^0.0.2
  agora_rtc_engine: 6.2.2
  connectycube_flutter_call_kit:
    path: ./dependencies/connectycube_flutter_call_kit-2.7.0
  event_bus: ^2.0.0
  #recording
  audio_waveforms: ^1.0.4
  # voice_message_package: ^2.1.4
  mime: ^1.0.5
  video_player: ^2.9.3
  chewie: ^1.7.5
  visibility_detector: ^0.4.0+2
  video_player_android: ^2.7.1

  socket_io_client: ^2.0.3+1

  voice_message_package:
    git:
      url: https://github.com/tohuyson/voice_message_player.git
      ref: master

  # Scroll
  infinite_scroll_pagination: ^4.0.0

  flutter_slidable: ^3.0.1
  audioplayers: ^5.2.1
  intl_phone_number_input:
    git:
      url: https://github.com/natintosh/intl_phone_number_input.git
      ref: v0.8.0 # tag
  permission_handler: ^11.3.0
  video_compress: ^3.1.3
  flutter_image_compress: ^2.1.0

  #  pip in app view
  pip_view: ^0.9.7
  grouped_list: ^5.1.2

  flutter_contacts: ^1.1.7+1
  wakelock_plus: ^1.1.4

  sliding_up_panel: ^2.0.0+1
  carousel_slider: ^4.2.1
  auto_size_text: ^3.0.0
  expandable_text: ^2.3.0

  image_gallery_saver: ^2.0.3

  styled_text: ^8.1.0
  any_link_preview: ^3.0.1
  html_unescape: ^2.0.0

  flutter_branch_sdk: ^7.1.0
  qr_flutter: ^4.1.0

  photo_view: ^0.15.0
  dismissible_page: ^1.0.2
  percent_indicator: ^4.2.3

  flutter_reaction_button: ^3.0.0+3
  stipop_sdk:
    path: ./dependencies/stipop_sdk
  # stipop_sdk: ^0.2.3
  jitsi_meet_flutter_sdk: ^0.4.1
  circle_flags: ^5.0.0
  story_view: ^0.16.5
  lottie: ^3.1.2
  slide_countdown: ^1.6.1
  change_app_package_name: ^1.4.0

  # map
  google_maps_flutter: ^2.5.0
  location: ^5.0.0

  #  FireBase
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  #live-stream
  bubbly_camera:
    path: "CameraPlugin/camera"
  qr_code_scanner: ^1.0.0
  shimmer: ^2.0.0
  flutter_video_info:
  video_thumbnail:
  flutter_downloader: ^1.11.6
  app_tracking_transparency: ^2.0.3
  marquee: ^2.2.0
  share_plus: ^7.2.2
  in_app_purchase: ^3.2.0
  cupertino_icons: ^1.0.2
  stacked: ^3.2.5
  detectable_text_field: ^3.0.2
  webview_flutter: ^3.0.4
  bouncing_widget: ^2.0.0
  audioplayers_darwin: ^5.0.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_local_notifications: ^18.0.1
  provider: ^6.1.2
  ffmpeg_kit_flutter_full: ^6.0.3
  like_button: ^2.0.5
  just_audio: ^0.9.42
  camera: ^0.10.5+2
  shared_preferences: ^2.2.2
  super_sliver_list: ^0.4.1
  smooth_list_view: ^2.0.1
  gallery_saver_plus: ^3.2.1
  hl_image_picker: ^1.2.16
  flutter_keyboard_visibility: ^6.0.0
  popover: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code generator
  build_runner: ^2.4.5
  freezed: ^2.4.6
  json_serializable: ^6.6.0
  flutter_gen_runner: ^5.2.0
  # dart_mappable_builder: ^3.1.1

  # lint
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.6.0

  # launcher icon & splash screen
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0

  mobile_scanner: ^5.1.1

  flutter_dynamic_icon: ^2.1.0
  animate_do: ^3.3.4
  wolt_modal_sheet: ^0.9.2
  receive_sharing_intent: ^1.8.0

  record: ^5.1.2

dependency_overrides:
  http: 0.13.5
  intl: 0.19.0
  fading_edge_scrollview: ^4.1.1

flutter_gen:
  output: lib/presentation/resource/gen
  line_lenght: 160
  null_safety: true

  integrations:
    flutter_svg: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: false

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env

    - assets/images/
    - assets/icons/
    - assets/illus/
    - assets/sounds/
    - assets/gif/
    - assets/lotties/

    - images/
    - icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 800 
