part of 'app_pages.dart';

class Routes {
  Routes._();

  static const splash = _Paths.splash;
  static const home = _Paths.home;
  static const login = _Paths.login;
  static const authOption = _Paths.authOption;
  static const register = _Paths.register;
  static const forgotPassword = _Paths.forgotPassword;
  static const referralId = _Paths.referralId;
  static const call = _Paths.call;
  static const otpReceive = _Paths.otpReceive;
  static const otpReceiveForgotPassword = _Paths.otpReceiveForgotPassword;
  static const resetPassword = _Paths.resetPassword;
  static const intro = _Paths.intro;
  static const profile = _Paths.profile;
  static const setting = _Paths.setting;
  static const chatDashboard = _Paths.chatDashboard;
  static const chatHub = _Paths.chatHub;
  static const conversationDetails = _Paths.conversationDetails;
  static const conversationMembers = _Paths.conversationMembers;
  static const conversationResources = _Paths.conversationResources;
  static const callGateway = _Paths.callGateway;
  static const searchContact = _Paths.searchContact;
  static const inComingCall = _Paths.inComingCall;
  static const search = _Paths.search;
  static const createPost = _Paths.createPost;
  static const editPost = _Paths.editPost;
  static const report = _Paths.report;
  static const posterPersonal = _Paths.posterPersonal;
  static const personalPage = _Paths.personalPage;
  static const postDetail = _Paths.postDetail;
  static const post = _Paths.post;
  static const notification = _Paths.notification;
  static const myProfile = _Paths.myProfile;
  static const mission = _Paths.mission;
  static const storyPage = _Paths.storyPage;
  static const createStory = _Paths.createStory;
  static const travelMiniApp = _Paths.travelMiniApp;
  static const travel = _Paths.createStory;
  static const travelLocation = _Paths.travelLocation;
  static const travelLocationFilter = _Paths.travelLocationFilter;
  static const mapLinking = _Paths.mapLinking;
  static const XINMeeting = _Paths.XINMeeting;
  static const cameraScreen = _Paths.cameraScreen;
}

class _Paths {
  _Paths._();

  static const splash = '/splash';
  static const home = '/home';
  static const login = '/login';
  static const authOption = '/auth-option';
  static const register = '/register';
  static const forgotPassword = '/forgot-password';
  static const otpReceive = '/otp-receive';
  static const otpReceiveForgotPassword = '/otp-receive-forgot-password';
  static const resetPassword = '/reset-password';
  static const intro = '/intro';
  static const profile = '/profile';
  static const setting = '/setting';
  static const chatDashboard = '/chat-dashboard';
  static const chatHub = '/chat-hub';
  static const conversationDetails = '/conversation-details';
  static const conversationMembers = '/conversation-members';
  static const conversationResources = '/conversation-resources';
  static const call = '/call';
  static const callGateway = '/call-gateway';
  static const searchContact = '/search-contact';
  static const inComingCall = '/in_coming_call';
  static const search = '/search';
  static const createPost = '/create-post';
  static const editPost = '/edit-post';
  static const report = '/report';
  static const posterPersonal = '/poster-personal';
  static const personalPage = '/personal-page';
  static const postDetail = '/post-detail';
  static const post = '/post';
  static const notification = '/notification';
  static const referralId = '/referral-id';
  static const myProfile = '/my-profile';
  static const mission = '/mission';
  static const storyPage = '/story-page';
  static const createStory = '/create-story';
  static const travelMiniApp = '/travel-mini-app';
  static const travelLocation = '/travelLocation';
  static const travelLocationFilter = '/travel-location-filter';
  static const mapLinking = '/map-linking';
  static const XINMeeting = '/xin-meeting';
  static const cameraScreen = '/camera-screen';
}
